@startuml
hide empty members
skinparam classAttributeIconSize 0

class CancerStage {
  cancerConditionAtDiagnosisReference : Reference(CancerConditionAtDiagnosis) [1..1]
  classificationType : codeableConcept [1..1]
  value : element [1..*]
  type : codeableConcept [1..1]
  evidenceReference : Reference(Surgery,Imaging) [0..*]  
}

note left of CancerStage::type
- Indicates whether the stage instance is of type Clinical or Pathological. 
- Choice: Clinical | Pathological
end note
@enduml
