@startuml
hide empty members
skinparam classAttributeIconSize 0

' Classes derived from logical models
class ActiveSurveillance [[StructureDefinition-ActiveSurveillance.html]]
class CancerConditionAtDiagnosis [[StructureDefinition-CancerConditionAtDiagnosis.html]]
class CancerPatient [[StructureDefinition-CancerPatient.html]]
class CancerStage [[StructureDefinition-CancerStage.html]]
class ClinicalCancerProgression [[StructureDefinition-ClinicalCancerProgression.html]]
class Imaging [[StructureDefinition-Imaging.html]]
class LastFollowUp [[StructureDefinition-LastFollowUp.html]]
class OverallCancerTreatmentResponse [[StructureDefinition-OverallCancerTreatmentResponse.html]]
class Radiotherapy [[StructureDefinition-Radiotherapy.html]]
class Surgery [[StructureDefinition-Surgery.html]]
class SystemicTreatment [[StructureDefinition-SystemicTreatment.html]]

' Relationships derived from Reference() fields
/' ActiveSurveillance --> CancerPatient
ActiveSurveillance --> CancerConditionAtDiagnosis
CancerConditionAtDiagnosis --> CancerPatient
CancerStage --> CancerConditionAtDiagnosis
CancerStage --> Surgery
note on link
onlyIfType=Pathological
end note
CancerStage --> Imaging
note on link
onlyIfType=Clinical
end note
ClinicalCancerProgression --> CancerConditionAtDiagnosis
LastFollowUp --> CancerPatient
OverallCancerTreatmentResponse --> CancerConditionAtDiagnosis
OverallCancerTreatmentResponse --> ClinicalCancerProgression
Radiotherapy --> CancerPatient
Radiotherapy --> CancerConditionAtDiagnosis
Radiotherapy --> ClinicalCancerProgression
Surgery --> CancerPatient
Surgery --> CancerConditionAtDiagnosis
Surgery --> ClinicalCancerProgression
SystemicTreatment --> CancerPatient
SystemicTreatment --> CancerConditionAtDiagnosis
SystemicTreatment --> ClinicalCancerProgression '/


abstract class CancerTreatment

CancerTreatment-u->CancerConditionAtDiagnosis
CancerTreatment --> CancerPatient
CancerConditionAtDiagnosis --> CancerPatient
CancerStage -u-> CancerConditionAtDiagnosis
CancerStage --> Surgery
note on link
onlyIfType=Pathological
end note
CancerStage --> Imaging
note on link
onlyIfType=Clinical
end note
ClinicalCancerProgression -u-> CancerConditionAtDiagnosis
LastFollowUp -u-> CancerPatient
OverallCancerTreatmentResponse -u-> CancerConditionAtDiagnosis
OverallCancerTreatmentResponse -u-> ClinicalCancerProgression
CancerTreatment --> ClinicalCancerProgression
CancerTreatment <|-- Radiotherapy
CancerTreatment <|-- SystemicTreatment
CancerTreatment <|-- Surgery
CancerTreatment <|-- ActiveSurveillance
note bottom of ActiveSurveillance
Applicable only before 
ClinicalCancerProgression.
Discontinued when progression occurs.
end note


@enduml
