@startuml
hide empty members
skinparam classAttributeIconSize 0

class ClinicalCancerProgression {
  cancerConditionAtDiagnosisReference : Reference(CancerConditionAtDiagnosis) [1..1]
  diseaseStatus : codeableConcept [1..1]
  tumourGradeSystem : codeableConcept [0..1]
  tumourGradeValue : string [0..1]
  assertedDate : dateTime [1..1]
  extentType : codeableConcept [0..1]
  locoRegionalSites : codeableConcept [0..*]
  metastaticSites : codeableConcept [0..*]
}

note left of ClinicalCancerProgression::diseaseStatus
Choice: Progression | Stable Disease 
| Partial Remission | Complete Remission | Recurrence
end note 
note left of ClinicalCancerProgression::extentType
extentType: Choice: Local | Loco-regional | Metastatic
end note
@enduml
