@startuml
top to bottom direction
hide methods
skinparam classAttributeIconSize 0

class "ClinicalCancerProgression3-Example" as ClinicalCancerProgression3 [[Binary-ClinicalCancerProgression3-Example.html]] {
  DiseaseStatus: Complete Remission
  AssertedDate: 2019-05-30
}

class "LastFollowUp3-Example" as LastFollowUp3 [[Binary-LastFollowUp3-Example.html]] {
  VitalStatus: Alive
  EvidenceOfDisease: False
  Date: 2019-05-30
}

class "CancerConditionAtDiagnosis1-Example" as CancerConditionAtDiagnosis1 [[Binary-CancerConditionAtDiagnosis1-Example.html]] {}
class "CancerPatient1-Example" as CancerPatient1 [[Binary-CancerPatient1-Example.html]] {}

ClinicalCancerProgression3 --> CancerConditionAtDiagnosis1 : CancerConditionAtDiagnosis
LastFollowUp3 --> CancerPatient1 : subject
@enduml