@startuml
top to bottom direction
hide methods
skinparam classAttributeIconSize 0

class "OverallCancerTreatmentResponse1-Example" as OverallCancerTreatmentResponse1 [[Binary-OverallCancerTreatmentResponse1-Example.html]] {
  TreatmentResponseType: Complete Remission
  Date: 2018-10-30
}

class "ClinicalCancerProgression1-Example" as ClinicalCancerProgression1 [[Binary-ClinicalCancerProgression1-Example.html]] {
  DiseaseStatus: Complete Remission
  AssertedDate: 2018-10-30
}

class "LastFollowUp1-Example" as LastFollowUp1 [[Binary-LastFollowUp1-Example.html]] {
  VitalStatus: Alive
  EvidenceOfDisease: False
  Date: 2018-10-30
}

class "CancerConditionAtDiagnosis1-Example" as CancerConditionAtDiagnosis1 [[Binary-CancerConditionAtDiagnosis1-Example.html]] {}
class "CancerPatient1-Example" as CancerPatient1 [[Binary-CancerPatient1-Example.html]] {}

OverallCancerTreatmentResponse1 --> CancerConditionAtDiagnosis1 : CancerConditionAtDiagnosis
ClinicalCancerProgression1 --> CancerConditionAtDiagnosis1 : CancerConditionAtDiagnosis
LastFollowUp1 --> CancerPatient1 : subject
@enduml