@startuml
hide empty members
skinparam classAttributeIconSize 0

class OverallCancerTreatmentResponse {
  cancerConditionAtDiagnosisReference : Reference(CancerConditionAtDiagnosis) [1..1]
  clinicalCancerProgressionReference : Reference(ClinicalCancerProgression) [0..1]
  treatmentResponseType : codeableConcept [1..1]
  date : dateTime [1..1]
}

note left of OverallCancerTreatmentResponse::treatmentResponseType
Choice: Progression | Stable Disease | Partial Remission | Complete Remission
end note
@enduml
