@startuml
hide empty members
skinparam classAttributeIconSize 0

class Surgery {
  subject : CancerPatient [1..1]
  cancerConditionAtDiagnosisReference : Reference(CancerConditionAtDiagnosis) [1..1]
  clinicalCancerProgressionReference : Reference(ClinicalCancerProgression) [0..1]
  intent : codeableConcept [1..1]
  date : dateTime [1..1]
  bodySite : codeableConcept [1..*]
}

note left of Surgery::intent
Choice: Definitive | Palliative 
end note
@enduml
